//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Produtoitau.Models
{
    using System;
    using System.Collections.Generic;
    
    public class Produtos
    {

        public int IDProduto { get; set; }
        public string Produto { get; set; }
        public string Categoria { get; set; }
        public Nullable<decimal> QtdeEstoque { get; set; }
        public Nullable<decimal> Preco { get; set; }
    }
}
